### ISSUE TITLE
howto update bitcoin-qt for the last version?

### ISSUE THREAD

**Issue by hcarrega** [okcashpro/ROKOS-OK-Bitcoin-Fullnode#11]
thanks

**Comment by hcarrega** [comment]
just see

**Comment by hcarrega** [comment]
update to 0.14.1 ??

**Comment by hcarrega** [comment]
Just follow steps and end in error on compiling

**Comment by ggBlaze** [comment]
please post your error (log), and which of the tutorials you followed to provide a proper answer. thx.

**Comment by hcarrega** [comment]
Problem solved . Thanks

**Comment by ggBlaze** [comment]
OK, Solved and closed.
