### ISSUE TITLE
DMD 2.1.0.3 mandatory update before 19th june

### ISSUE THREAD

**Issue by cryptonit** [okcashpro/ROKOS-OK-Bitcoin-Fullnode#4]
DMD 2.1.0.3 mandatory update before 19th june
https://bitcointalk.org/index.php?topic=1084908.msg15123657#msg15123657

**Comment by ggBlaze** [comment]
Understood, thank you for your update, will get an updated binary for the users and will get updated for the coming release.

**Comment by ggBlaze** [comment]
Updated DMD Binaries to 2.1.0.3:
https://github.com/BitcoinFullnode/ROKOS-OK-Bitcoin-Fullnode/commit/1d82da136aee0e58ca7302cf6fa6f0f048da7278

Instructions on how to update the ROKOS System with it over the tutorials section of this github.
