### ISSUE TITLE
DMD 2.1.0.4 update to avoid sync issue of historic blocks is required

### ISSUE THREAD

**Issue by cryptonit** [okcashpro/ROKOS-OK-Bitcoin-Fullnode#5]
https://bitcointalk.org/index.php?topic=580725.msg15514254#msg15514254

**Comment by ggBlaze** [comment]
Thanks for the update, will be releasing the binaries for update and latest update should bet included in the coming ROKOS Flavors version.

**Comment by ggBlaze** [comment]
Upgraded on v8 flavors. 👌
