### ISSUE TITLE
ROKOS freezes and won't wake up while syncing BTC blockchain.

### ISSUE THREAD

**Issue by partsoven** [okcashpro/ROKOS-OK-Bitcoin-Fullnode#6]
Love this project. Not only a promising BTC node, but a beautiful deployment of linux on pi.

I have been trying to sync Bitcoin Core for a few weeks now using a 256GB SanDisk flash drive. It is well over half synced, but when I leave it to sync over the weekend it goes to sleep and won't wake back up. The green CPU LED is lit solid so it looks like it is just being over taxed?

First thought is maybe its overheating? My raspbi 3.0 has no fan. Do I need one?

Have you guys been able to download and sync the entire BTC blockchain on a pi?

When I unplug and plug it back in it starts syncing again 1 year ago.

**Comment by ggBlaze** [comment]
local issue, solved over the live support channels at: https://discord.gg/VSTKsZa if require further assistance can also start thread for support over: https://okcashtalk.org/index.php#c6 (required dbcache over config file)
