### ISSUE TITLE
Kernel

### ISSUE THREAD

**Issue by Tomcatt** [okcashpro/ROKOS-OK-Bitcoin-Fullnode#7]
Hello, I used the ROKOS Flavor image and as soon as the Raspberry Pi 2 boots, I get a kernel panic. 

"not syncing - no working init found.  try passing init = option to kernel. "

**Comment by ggBlaze** [comment]
Hi, please check the download with the checksum to ensure is not corrupted, then make sure you are using a 2.5 power cable for the pi, the ROKOS v8 core image is tested under Pi 2 and Pi 3 Devices.
Can also try powering it up without any plugged usb, but it sounds more as a corrupted image burn.

**Comment by Tomcatt** [comment]
I found out what it was.  Because I started burning it with watching, it was stopping too soon.  So I just had to make the SD card a different way and now it's fine.  Thanks 

Before I close it off topic, what do you think of the Odroid-C2 and the Parallella Computer?
